source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'hole19v2' do
    pod 'SDWebImage'

    target 'hole19v2Tests' do
        pod 'Nimble', '3.2.0'
        pod 'Quick'
    end

end